# Generated by Django 4.1 on 2022-12-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=15)),
                ('fecha_inscripcion', models.DateField()),
                ('institucion', models.CharField(max_length=30)),
                ('hora_inscripcion', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=40)),
            ],
        ),
    ]
