# Generated by Django 4.1 on 2022-12-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Templates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Reservas',
        ),
    ]
